// Autogenerated

#ifndef CLIENTSLIST_H
#define CLIENTSLIST_H

#include <QAbstractListModel>
#include <QObject>
#include <QVector>

#include "..\types.h"

class ClientsList : public QAbstractListModel
{
	Q_OBJECT
public:
	ClientsList() {}
	ClientsList(const QVector<Client>& list);
	void append(const Client& item);

public:
	enum roles
	{
		NameRole = Qt::UserRole + 1,
		AddressRole
	};

	int rowCount(const QModelIndex &parent) const { Q_UNUSED(parent); return _clients.count(); }
	QVariant data(const QModelIndex &index, int role) const;
	QHash<int, QByteArray> roleNames() const;

private:
	QVector<Client> _clients;
};

#endif // CLIENTSLIST_H
