// Autogenerated

#include "clientslist.h"

ClientsList::ClientsList(const QVector<Client>& list)
{
	for (const auto& item : list)
	{
		_clients.append(item);
	}
}

void ClientsList::append(const Client& item)
{
	_clients.append(item);
}

QVariant ClientsList::data(const QModelIndex &index, int role) const
{
	switch (role) {
	case roles::NameRole:
		return QVariant::fromValue(_clients[index.row()].name);
	case roles::AddressRole:
		return QVariant::fromValue(_clients[index.row()].address);
	default: return QVariant();
	}
}

QHash<int, QByteArray> ClientsList::roleNames() const
{
	QHash<int, QByteArray> names;

	names[roles::NameRole] = "name";
	names[roles::AddressRole] = "address";

	return names;
}
