// Autogenerated

#ifndef CLIENTSLIST_H
#define CLIENTSLIST_H

#include <QAbstractListModel>
#include <QVector>

#include "..\types.h"

class ClientsList : public QAbstractListModel
{
    Q_OBJECT
public:
    ClientsList(QObject *parent = nullptr) : QAbstractListModel(parent) {}
	ClientsList(const QVector<Client>& list);
    void append(const Client& item, bool supressUpdate = false);
    void append(const QVector<Client>& list);
    void clear();

public:
	enum roles
	{
        IdRole = Qt::UserRole + 1,
        NameRole,
        AddressRole,
        SummaryRole
	};

	int rowCount(const QModelIndex &parent) const { Q_UNUSED(parent); return _clients.count(); }
	QVariant data(const QModelIndex &index, int role) const;
	QHash<int, QByteArray> roleNames() const;

private:
	QVector<Client> _clients;
};

#endif // CLIENTSLIST_H
