// Autogenerated

#include "driverslist.h"

DriversList::DriversList(const QVector<Driver>& list)
{
	for (const auto& item : list)
	{
		_drivers.append(item);
	}
}

void DriversList::append(const Driver& item)
{
	_drivers.append(item);
}

QVariant DriversList::data(const QModelIndex &index, int role) const
{
	switch (role) {
	case roles::NameRole:
		return QVariant::fromValue(_drivers[index.row()].name);
	case roles::ContractDateRole:
		return QVariant::fromValue(_drivers[index.row()].contractDate);
	default: return QVariant();
	}
}

QHash<int, QByteArray> DriversList::roleNames() const
{
	QHash<int, QByteArray> names;

	names[roles::NameRole] = "name";
	names[roles::ContractDateRole] = "contractDate";

	return names;
}
