// Autogenerated

#ifndef DRIVERSLIST_H
#define DRIVERSLIST_H

#include <QAbstractListModel>
#include <QObject>
#include <QVector>

#include "..\types.h"

class DriversList : public QAbstractListModel
{
	Q_OBJECT
public:
	DriversList() {}
	DriversList(const QVector<Driver>& list);
	void append(const Driver& item);

public:
	enum roles
	{
		NameRole = Qt::UserRole + 1,
		ContractDateRole
	};

	int rowCount(const QModelIndex &parent) const { Q_UNUSED(parent); return _drivers.count(); }
	QVariant data(const QModelIndex &index, int role) const;
	QHash<int, QByteArray> roleNames() const;

private:
	QVector<Driver> _drivers;
};

#endif // DRIVERSLIST_H
