// Autogenerated

#ifndef ORDERSLIST_H
#define ORDERSLIST_H

#include <QAbstractListModel>
#include <QObject>
#include <QVector>

#include "..\types.h"

class OrdersList : public QAbstractListModel
{
	Q_OBJECT
public:
	OrdersList() {}
	OrdersList(const QVector<Order>& list);
	void append(const Order& item);

public:
	enum roles
	{
		DriverNameRole = Qt::UserRole + 1,
		DriverContractDateRole,
		TruckModelRole,
		TruckNumberRole,
		TruckLastMilageRole,
		TruckLastMaintananceDateRole,
		FromNameRole,
		FromAddressRole,
		ToNameRole,
		ToAddressRole,
		CreatedAtRole,
        CreatedAtStringRole,
		SentAtRole,
        SentAtStringRole,
		ReceivedAtRole,
        ReceivedAtStringRole,
		FinishedRole,
		DistanceRole,
		DescriptionRole,
		ValueRole
	};

	int rowCount(const QModelIndex &parent) const { Q_UNUSED(parent); return _orders.count(); }
	QVariant data(const QModelIndex &index, int role) const;
	QHash<int, QByteArray> roleNames() const;

private:
	QVector<Order> _orders;
};

#endif // ORDERSLIST_H
