// Autogenerated

#ifndef REFUELINGSLIST_H
#define REFUELINGSLIST_H

#include <QAbstractListModel>
#include <QObject>
#include <QVector>

#include "..\types.h"

class RefuelingsList : public QAbstractListModel
{
	Q_OBJECT
public:
	RefuelingsList() {}
	RefuelingsList(const QVector<Refueling>& list);
	void append(const Refueling& item);

public:
	enum roles
	{
		DriverNameRole = Qt::UserRole + 1,
		DriverContractDateRole,
		DateRole,
		CostRole
	};

	int rowCount(const QModelIndex &parent) const { Q_UNUSED(parent); return _refuelings.count(); }
	QVariant data(const QModelIndex &index, int role) const;
	QHash<int, QByteArray> roleNames() const;

private:
	QVector<Refueling> _refuelings;
};

#endif // REFUELINGSLIST_H
