// Autogenerated

#include "refuelingslist.h"

RefuelingsList::RefuelingsList(const QVector<Refueling>& list)
{
	for (const auto& item : list)
	{
		_refuelings.append(item);
	}
}

void RefuelingsList::append(const Refueling& item)
{
	_refuelings.append(item);
}

QVariant RefuelingsList::data(const QModelIndex &index, int role) const
{
	switch (role) {
	case roles::DriverNameRole:
		return QVariant::fromValue(_refuelings[index.row()].driverName);
	case roles::DriverContractDateRole:
		return QVariant::fromValue(_refuelings[index.row()].driverContractDate);
	case roles::DateRole:
		return QVariant::fromValue(_refuelings[index.row()].date);
	case roles::CostRole:
		return QVariant::fromValue(_refuelings[index.row()].cost);
	default: return QVariant();
	}
}

QHash<int, QByteArray> RefuelingsList::roleNames() const
{
	QHash<int, QByteArray> names;

	names[roles::DriverNameRole] = "driverName";
	names[roles::DriverContractDateRole] = "driverContractDate";
	names[roles::DateRole] = "date";
	names[roles::CostRole] = "cost";

	return names;
}
