// Autogenerated

#ifndef TRUCKSLIST_H
#define TRUCKSLIST_H

#include <QAbstractListModel>
#include <QObject>
#include <QVector>

#include "..\types.h"

class TrucksList : public QAbstractListModel
{
	Q_OBJECT
public:
	TrucksList() {}
	TrucksList(const QVector<Truck>& list);
	void append(const Truck& item);

public:
	enum roles
	{
		ModelRole = Qt::UserRole + 1,
		NumberRole,
		LastMileageRole,
		LastMaintananceDateRole
	};

	int rowCount(const QModelIndex &parent) const { Q_UNUSED(parent); return _trucks.count(); }
	QVariant data(const QModelIndex &index, int role) const;
	QHash<int, QByteArray> roleNames() const;

private:
	QVector<Truck> _trucks;
};

#endif // TRUCKSLIST_H
